import {StyleSheet} from 'react-native';
import {globalStyles} from '../../constants/globalStyles';

export const styles = StyleSheet.create({
  root: {
    overflow: 'hidden',
    flex: 1,
    backgroundColor: '#101e17',
  },
  container: {
    padding: 24,
  },
  backgroundImage: {
    position: 'absolute',
    zIndex: 1,
    width: '100%',
    height: 490,
  },
  top: {
    marginTop: 200,
  },
  brush: {
    position: 'absolute',
    width: 150,
    right: 32,
    top: 36,
  },
  title: {
    ...globalStyles.rubik300,
    color: '#fff',
    fontSize: 27,
    lineHeight: 32,
  },
  titleBold: {
    ...globalStyles.rubik700,
    fontSize: 30,
    lineHeight: 46.8,
  },
  subTitle: {
    ...globalStyles.rubik300,
    fontSize: 17,
    lineHeight: 24,
    letterSpacing: 0.38,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  content: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  mainImage: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    width: 375,
    height: 530,
    marginTop: 12,
  },
  featureListItem: {
    width: 156,
    height: 130,
    marginRight: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    backdropFilter: 'blur(8px)',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    borderBottomLeftRadius: 14,
    display: 'flex',
    padding: 16,
    marginTop: 20,
    marginBottom: 20,
  },
  featureListItemIcon: {
    marginBottom: 16,
  },
  featureListItemTitle: {
    ...globalStyles.rubik500,
    fontSize: 20,
    lineHeight: 24,
    color: '#fff',
  },
  featureListItemSubTitle: {
    ...globalStyles.rubik400,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.08,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  paywallOption: {
    position: 'relative',
    width: '100%',
    height: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    borderStyle: 'solid',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    borderBottomLeftRadius: 14,
    marginBottom: 16,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
  },
  paywallOptionSelected: {
    borderWidth: 1.5,
    borderColor: '#28AF6E',
  },
  paywallOptionTitle: {
    ...globalStyles.rubik500,
    fontSize: 16,
    lineHeight: 19,
    color: '#FFFFFF',
  },
  paywallOptionSubTitle: {
    ...globalStyles.rubik400,
    fontSize: 12,
    lineHeight: 14,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  paywallOptionBadge: {
    position: 'absolute',
    right: 0,
    top: 0,
    backgroundColor: '#28AF6E',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 14,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 20,
    paddingLeft: 12,
    paddingTop: 4,
    paddingBottom: 4,
    paddingRight: 9,
  },
  paywallOptionBadgeText: {
    ...globalStyles.rubik500,
    fontSize: 12,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  note: {
    ...globalStyles.rubik300,
    fontSize: 9,
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 0.52)',
    marginTop: 8,
  },
  links: {
    ...globalStyles.rubik400,
    marginTop: 10,
    fontSize: 11,
    lineHeight: 13,
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 0.5)',
  },
  closeButton: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
    top: 55,
    right: 16,
  },
});
